[package]
name = "code_atlas"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
license = "GPL-3.0-or-later"

[lints]
workspace = true

[lib]
path = "src/code_atlas.rs"

[dependencies]
anyhow.workspace = true
bytecount = "0.6"
db.workspace = true
gpui.workspace = true
log.workspace = true
project.workspace = true
smol.workspace = true
streemap = "0.1"
ui.workspace = true
workspace.workspace = true
worktree.workspace = true
theme.workspace = true

[dev-dependencies]
db = { workspace = true, features = ["test-support"] }
